name: 'S3 mirror upload'
description: 'Deploy to S3 compatible Storage'
author: 'herbetom'
inputs:
  endpoint:
    description: 'Endpoint URL of the object storage host (including https://)'
    required: true
  access_key:
    description: 'Access key (username)'
    required: true
  secret_key:
    description: 'Secret key (password)'
    required: true
  bucket:
    description: 'Set the target bucket for deployment.'
    required: true
  region:
    description: 'S3 region (optional)'
    required: false
    default: ''
  source_dir:
    description: 'Set an input directory for deployment.'
    required: false
    default: 'public'
  target_dir:
    description: 'Set a target directory for deployment (with a leading slash).'
    required: false
    default: '/'
  mode:
    description: '"copy" (never deletes) or "sync" (deletes remote files missing locally)'
    required: false
    default: 'copy'
  extra_args:
    description: 'Add additional Args to the rclone command'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    S3_ENDPOINT: ${{ inputs.endpoint }}
    S3_ACCESS_KEY: ${{ inputs.access_key }}
    S3_SECRET_KEY: ${{ inputs.secret_key }}
    S3_REGION: ${{ inputs.region }}
    RCLONE_MODE: ${{ inputs.mode }}
  args:
    - ${{ inputs.source_dir }}
    - '${{ inputs.bucket }}${{ inputs.target_dir }}'
    - ${{ inputs.extra_args }}
branding:
  icon: 'upload-cloud'
  color: 'black'
